version: '3'

services:
  primary:
    image: livingdocs/postgres:15.0
    ports: [5432:5432]
    restart: on-failure
    volumes:
      - ./primary-postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  replica:
    image: livingdocs/postgres:15.0
    ports: [5433:5432]
    restart: on-failure
    volumes:
      - ./replica-postgresql:/var/lib/postgresql
    command: standby -d "host=primary port=5432 user=postgres password=${POSTGRES_PASSWORD} target_session_attrs=read-write"
