#!/bin/bash
set -eu
if [ "$(id -u)" == "0" ] ; then exec su-exec postgres "$BASH_SOURCE" "$@"; fi

URL="${FETCH_CERTIFICATE_URL:-https://certificates.production.livingdocs.io/list}"
TOKEN="${FETCH_CERTIFICATE_TOKEN:-SOME TOKEN}"
FILE="${FETCH_CERTIFICATE_FILE:-<domain>}"

RES=$(curl --fail -s -H "Authorization: Bearer $TOKEN" $URL)
CERTIFICATE=$(jq -rj '.[0]' <<< "$RES")
DOMAIN=$(jq -r '.domain' <<< "$CERTIFICATE")
FILE=$(sed "s/<domain>/$DOMAIN/" <<< "$FILE")

echo Downloaded $FILE.key and $FILE.cert
jq -r '.key' <<< "$CERTIFICATE" > $FILE.key
jq -r '.cert' <<< "$CERTIFICATE" > $FILE.cert
chmod 0600 $FILE.key $FILE.cert
pg_ctl reload
