#!/bin/bash
set -Eeo pipefail
if [ "$(id -u)" != "1000" ] ; then exec su-exec postgres "$BASH_SOURCE" "$@"; fi

TRUST=$1
if [ "$1" != "trust" ]; then TRUST=md5; fi

cat <<EOF > $PGDATA/pg_hba.conf
# TYPE  DATABASE      USER    ADDRESS         METHOD
local   all           all                     trust
host    all           all     127.0.0.1/32    trust
host    all           all     ::1/128         trust
host    all           all     0.0.0.0/0       $TRUST
host    all           all     ::0/0           $TRUST

# And the same against the for replication connections,
# which are handled separately. 'replication' is a special keyword here.
local   replication   all                     trust
host    replication   all     127.0.0.1/32    trust
host    replication   all     ::1/128         trust
host    replication   all     0.0.0.0/0       $TRUST
host    replication   all     ::0/0           $TRUST
EOF

chmod 0600 $PGDATA/pg_hba.conf
