#!/bin/bash
set -eu
set -o pipefail

export DEBIAN_FRONTEND=noninteractive
apt-get update && apt-get upgrade -y

groupadd -r postgres --gid=1000
useradd -r -g postgres --uid=1000 --home-dir=/var/lib/postgresql --shell=/bin/bash postgres

mkdir -p /var/lib/postgresql /var/run/postgresql /var/lib/postgresql/initdb.d
chown -R postgres:postgres /var/lib/postgresql /var/run/postgresql
apt-get install -y --no-install-recommends curl nano pspg procps gosu dnsutils gnupg git ca-certificates

>&2 echo "Install Postgres"
echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main 16" > /etc/apt/sources.list.d/pgdg.list
curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/pgdg.gpg

apt-get update
apt-get install -y --no-install-recommends postgresql-common
sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf
apt-get install -y --no-install-recommends "postgresql-16=16.4-1.pgdg120+2"

>&2 echo 'Install pg_auto_failover'
apt-get install -y --no-install-recommends pg-auto-failover-cli postgresql-16-auto-failover

>&2 echo 'Install wal-g'
archfile=wal-g-fdb-ubuntu-20.04-amd64
if [ "$(uname -m)" == "aarch64" ]; then archfile=wal-g-fdb-ubuntu20.04-aarch64; fi
curl -s -L "https://github.com/wal-g/wal-g/releases/download/v3.0.3/$archfile" > /usr/local/bin/wal-g
chmod +x /usr/local/bin/wal-g
# We need to have locales enabled for postgres
grep -q '/usr/share/locale' /etc/dpkg/dpkg.cfg.d/docker || sed -ri '/\/usr\/share\/locale/d' /etc/dpkg/dpkg.cfg.d/docker
! grep -q '/usr/share/locale' /etc/dpkg/dpkg.cfg.d/docker
apt-get update
apt-get install -y --no-install-recommends locales
localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

>&2 echo "Cleanup"
apt-get purge -y --auto-remove apt-transport-https gnupg git
apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/log/*
