#!/bin/bash
set -Eeo pipefail
if [ "$(id -u)" != "1000" ] ; then exec gosu postgres "$BASH_SOURCE" "$@"; fi
source /usr/local/bin/docker-entrypoint.sh

# When recovering, the database directory must be empty
docker_create_db_directories

# if wal-g is configured, fetch the latest backup using that
# instead of pg_basebackup as it's much faster
if false; then
  wal-g backup-fetch "$PGDATA" LATEST --config="$WALG_CONFIG_FILE"
  # set promote_trigger_file in config
else
  # Fetch most recent full backup if there's no data present
  exec pg_basebackup -w -D "$PGDATA" -X stream "$@"
fi
